<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>numero_resultados</name>
   <tag></tag>
   <elementGuidId>f924c9c2-62cd-4204-9ba0-1cf4f027a680</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='default']/div/div/div/div/form/strong</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form.form-horizontal > strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>55f6add3-4fd6-46d7-90be-1643b84f3ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>7d8aa501-997f-4eb6-a164-bcbef4050e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;default&quot;)/div[@class=&quot;container-fluid page&quot;]/div[@class=&quot;page_inner&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-8 col-md-9&quot;]/form[@class=&quot;form-horizontal&quot;]/strong[1]</value>
      <webElementGuid>61287b10-f2e1-45e5-9a64-332bcc17923a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='default']/div/div/div/div/form/strong</value>
      <webElementGuid>f152bdda-bdb3-44c2-ac05-62535fa9cc71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mystery'])[3]/following::strong[1]</value>
      <webElementGuid>9171fc2c-c91e-4d50-b42a-234457743690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warning!'])[1]/preceding::strong[3]</value>
      <webElementGuid>4dfe41fa-0b21-4717-a65a-8d25790c4c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sharp Objects'])[1]/preceding::strong[4]</value>
      <webElementGuid>2a545fd8-eba7-49e7-9bb9-878901fc1fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='32']/parent::*</value>
      <webElementGuid>e8a7b812-6b48-4979-9097-e8a8319f0a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/strong</value>
      <webElementGuid>b008d3d3-7578-4613-8782-f2d9039ff3a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = '32' or . = '32')]</value>
      <webElementGuid>02e91097-31aa-4f92-8dcc-29cbfe8d8820</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
