<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>precio_article_detail</name>
   <tag></tag>
   <elementGuidId>143b7f74-8dfc-4fca-8c3c-e57995c1ec72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content_inner&quot;]/article/div[1]/div[2]/p[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.price_color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>0591a28f-5899-4dac-ae4e-b7b2b0396f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price_color</value>
      <webElementGuid>a4421d4b-fc24-46d0-b7ef-3a2e83ba8900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>£45.17</value>
      <webElementGuid>f9dbef89-f319-4cb9-aa62-d019e2fede1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content_inner&quot;)/article[@class=&quot;product_page&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 product_main&quot;]/p[@class=&quot;price_color&quot;]</value>
      <webElementGuid>cca3d33b-19b6-49e6-85b2-663af5fdbef7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content_inner']/article/div/div[2]/p</value>
      <webElementGuid>9b362c31-17c9-447a-b4aa-b0ea6bd60b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('It', &quot;'&quot;, 's Only the Himalayas')])[2]/following::p[1]</value>
      <webElementGuid>bfc8c1cd-c320-4d7a-8d4b-f7d5ff859892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('It', &quot;'&quot;, 's Only the Himalayas')])[1]/following::p[1]</value>
      <webElementGuid>071eab60-1298-4c2c-9669-28cb2391e8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warning!'])[1]/preceding::p[3]</value>
      <webElementGuid>7e3dfcd5-2a63-423f-b069-905d57924149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Description'])[1]/preceding::p[3]</value>
      <webElementGuid>da51eb24-7b85-4dbc-9c0b-a0367958ef5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='£45.17']/parent::*</value>
      <webElementGuid>364dcfa4-ace7-42b2-b99e-a060aad07b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>9db280ad-9e55-4ac0-8396-77d4cab2e281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '£45.17' or . = '£45.17')]</value>
      <webElementGuid>13e293d9-e044-4302-be22-dfff9f3c7053</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
