<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>priceResult</name>
   <tag></tag>
   <elementGuidId>197bbf92-c91d-4d7d-a5ec-50fd972a934b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.price_color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>#default > div.container-fluid.page > div > div > div > section > div:nth-child(2) > ol > li:nth-child(2) > article > div.product_price > p.price_color</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div/section/div[2]/ol/li[${number}]/article/div[2]/p[1][count(. | //*[@class = 'price_color']) = count(//*[@class = 'price_color'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>926b647c-980f-48d7-bbd0-b6a87acc46a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price_color</value>
      <webElementGuid>7fe442de-9a65-4c94-a918-587f3973b58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>£45.17</value>
      <webElementGuid>b07bc58f-c92b-4827-9796-58d931da577c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div/section/div[2]/ol/li[${number}]/article/div[2]/p[1]</value>
      <webElementGuid>7fb3c53a-db4e-449b-b1a1-a9e70b695c39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='default']/div/div/div/div/section/div[2]/ol/li/article/div[2]/p</value>
      <webElementGuid>2bc67792-caf1-4dc0-ba8b-df31477acfe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('It', &quot;'&quot;, 's Only the Himalayas')])[1]/following::p[1]</value>
      <webElementGuid>74405940-b1a5-40e1-8a5a-d5b05891f28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warning!'])[1]/following::p[2]</value>
      <webElementGuid>0442d452-f5cd-4ecf-9241-6849ece1258c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to basket'])[1]/preceding::p[2]</value>
      <webElementGuid>310fc247-d278-4c58-823e-aff5e83f5a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full Moon over Noah’s ...'])[1]/preceding::p[3]</value>
      <webElementGuid>79af8665-9fbe-4b86-9863-22d63ab610c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='£45.17']/parent::*</value>
      <webElementGuid>4710bfa8-5d74-4645-9e0b-6b6e64422616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>911697a5-4122-434b-9909-68cd3a47ee4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '£45.17' or . = '£45.17')]</value>
      <webElementGuid>76d4f76c-dd42-4d7a-afdb-e6394a5ce6ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
