<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Titulo-seccion</name>
   <tag></tag>
   <elementGuidId>3e7fe43e-3643-465a-94a9-551b001d484e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//center[@id='conten']/div/div/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${titulo_seccion}' or . = '${titulo_seccion}') and @ref_element = 'Object Repository/Page_Dolarsi/iframe_Precio del Dlar HOY en Argentina_frame-tool']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.header-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b719b55a-e6be-4108-9e1a-a5db46d5e391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-text</value>
      <webElementGuid>ae135125-e9fc-4c51-8c55-0c8a16125ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${titulo_seccion}</value>
      <webElementGuid>73d8eb3f-4859-4115-860b-dd4e3b794d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;conten&quot;)/div[@class=&quot;conte&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;header-text&quot;]</value>
      <webElementGuid>a661267a-4538-4806-bcbe-58d5cb9da8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DolarSi/Page_Dolarsi/iframe_Precio del Dlar HOY en Argentina_frame-tool</value>
      <webElementGuid>118cf356-5cf7-41ad-9a8d-dd8ec48236a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//center[@id='conten']/div/div/div[2]</value>
      <webElementGuid>ed158c15-ba04-4405-9a0a-7e8f81f9c7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMPRA'])[1]/preceding::div[1]</value>
      <webElementGuid>783d44e6-4ed4-40b4-b7f4-c0b9e76aa832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 347,02'])[1]/preceding::div[2]</value>
      <webElementGuid>1056c522-016a-46ab-8d7d-435b565b3403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DOLAR OFICIAL']/parent::*</value>
      <webElementGuid>ed47ed77-b498-4967-90ab-cda4b90a70b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]</value>
      <webElementGuid>946c389e-ba7d-4c1c-89cd-67a7b71270b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DOLAR OFICIAL' or . = 'DOLAR OFICIAL')]</value>
      <webElementGuid>041c7289-ecb4-4609-96ae-a3506b31e7a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
