<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Precio del Dlar HOY en Argentina_frame-tool</name>
   <tag></tag>
   <elementGuidId>9a378cc7-2bdf-4116-83ae-740f5fe5bf3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frame-tool</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='frame-tool']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4816e053-2b85-426b-8965-2f975c9b8771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frame-tool</value>
      <webElementGuid>52e3de58-4cbb-4b8d-9a2e-9912cb068127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>frametoolbar</value>
      <webElementGuid>ad26b375-9022-42ab-b521-5dcfffb60817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.dolarsi.com/func/tool4.php</value>
      <webElementGuid>f913ea03-67df-4b57-bfd8-ecf3542673f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>25a4989a-56ce-4318-bebd-c8cd86c4fafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>allowfullscreen</value>
      <webElementGuid>12feb487-1113-4862-9784-a6c134c95a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frame-tool&quot;)</value>
      <webElementGuid>6e98cd9b-5b18-4caf-89f9-676ae6aeb49c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='frame-tool']</value>
      <webElementGuid>01235cfa-d2f9-43a9-bf57-94816485e633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/p[2]/iframe</value>
      <webElementGuid>2e3311ff-aa60-4b23-ab8c-ead7fcb0ed6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/iframe</value>
      <webElementGuid>869d2785-8b3f-4fc6-824d-75d78fadb0eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'frame-tool' and @src = 'https://www.dolarsi.com/func/tool4.php']</value>
      <webElementGuid>df526c9e-ddbe-42ce-b4f4-64bb54ad964c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
