<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>precio_articulo</name>
   <tag></tag>
   <elementGuidId>0baf1611-a4ca-4cf7-a1c0-892d33daf064</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.price_color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='default']/div/div/div/div/section/div[2]/ol/li/article/div[2]/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '£45.17' or . = '£45.17')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6688edb0-d1c3-4fc5-aeb8-21252617e648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price_color</value>
      <webElementGuid>4f655fa6-4342-4796-86dc-c10e968a6c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>£45.17</value>
      <webElementGuid>6a4669a4-2004-4b57-8cdc-3e8325131af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;default&quot;)/div[@class=&quot;container-fluid page&quot;]/div[@class=&quot;page_inner&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-8 col-md-9&quot;]/section[1]/div[2]/ol[@class=&quot;row&quot;]/li[@class=&quot;col-xs-6 col-sm-4 col-md-3 col-lg-3&quot;]/article[@class=&quot;product_pod&quot;]/div[@class=&quot;product_price&quot;]/p[@class=&quot;price_color&quot;]</value>
      <webElementGuid>dc338e72-5328-4790-878f-86e0016d2ced</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='default']/div/div/div/div/section/div[2]/ol/li/article/div[2]/p</value>
      <webElementGuid>937f20c0-21b3-4ab0-b196-4aa90f776ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('It', &quot;'&quot;, 's Only the Himalayas')])[1]/following::p[1]</value>
      <webElementGuid>537061aa-9a97-48ca-9141-df653a789254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warning!'])[1]/following::p[2]</value>
      <webElementGuid>fa2b5764-9ecf-40b7-8d27-2b5c34beb985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to basket'])[1]/preceding::p[2]</value>
      <webElementGuid>3b9d6110-4ad0-4207-a8b0-f2293481664e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full Moon over Noah’s ...'])[1]/preceding::p[3]</value>
      <webElementGuid>d5f85e9c-0979-4052-88bd-aa9fd9a99289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='£45.17']/parent::*</value>
      <webElementGuid>8c70ec10-ebdb-4943-804f-a710ae6ace61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>a51cd4af-fe5f-4a32-9a56-59d53ebf4892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '£45.17' or . = '£45.17')]</value>
      <webElementGuid>41922f53-8173-40d1-9d53-342fa16e2dc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
